USE temp;

CREATE TABLE STUDENTS(
roll INT PRIMARY KEY,
name VARCHAR(25),
marks INT
);

INSERT INTO STUDENTS VALUES(101,'Aman',76);
INSERT INTO STUDENTS VALUES(102,'Aman',93);
INSERT INTO STUDENTS VALUES(103,'Aman',85);
INSERT INTO STUDENTS VALUES(104,'Aman',92);
INSERT INTO STUDENTS VALUES(105,'Aman',87);
INSERT INTO STUDENTS VALUES(106,'Aman',82);

UPDATE STUDENTS
SET name = 'Robert'
WHERE roll = 106;

ALTER TABLE STUDENTS
CHANGE stu_name name VARCHAR(25);

SELECT name,roll FROM STUDENTS
WHERE roll IN (SELECT roll FROM STUDENTS WHERE roll%2 = 0);

