CREATE DATABASE temp1;

USE temp1;
CREATE TABLE STUDENT(
  student_id INT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  department VARCHAR(20),
  admission_date DATE,
  email VARCHAR(50) UNIQUE
);

CREATE TABLE COURSE(
  course_id INT PRIMARY KEY,
  course_name VARCHAR(50),
  credits INT
);

CREATE TABLE ENROLLMENT(
  enroll_id INT PRIMARY KEY,
  student_id INT,
  course_id INT,
  grade VARCHAR(2),
  FOREIGN KEY(student_id) REFERENCES STUDENT(student_id),
  FOREIGN KEY(course_id) REFERENCES COURSE(course_id)
);

INSERT INTO STUDENT VALUES(1,'Rounak','CSE','2023-08-18','rounak@gmail.com');
INSERT INTO STUDENT VALUES(2,'Sagnik','CSE','2023-08-16','sagnik@gmail.com');
INSERT INTO STUDENT VALUES(6,'Ashmita','ME','2023-08-22','ashmita@gmail.com');
INSERT INTO STUDENT VALUES(7,'Bubun','ECE','2023-09-02','bubun@gmail.com');
INSERT INTO STUDENT VALUES(5,'Snehan','ECE','2023-08-16','snehan@gmail.com');
INSERT INTO STUDENT VALUES(4,'Sneha','ECE','2023-08-16','sneha@gmail.com');

INSERT INTO COURSE VALUES(001,'AI&ML',4);
INSERT INTO COURSE VALUES(002,'Cyber Scurity',3);
INSERT INTO COURSE VALUES(003,'Data Science',3.5);

INSERT INTO ENROLLMENT VALUES(120,1,001,8);
INSERT INTO ENROLLMENT VALUES(121,6,001,9);
INSERT INTO ENROLLMENT VALUES(122,5,003,10);
INSERT INTO ENROLLMENT VALUES(123,2,002,7);
INSERT INTO ENROLLMENT VALUES(125,7,003,6);

DELETE FROM ENROLLMENT WHERE enroll_id = 124;

